version: "3"
services:
  api:
    build: ./netflix-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: blog-api
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: myflix